### ISSUE TITLE
建议：注意尊重版权

### ISSUE THREAD

**Issue by bruceFend** [doocs/technical-books#4]
虽然大佬的初衷不错，但我看到有些书刚上市不久，就这样公开传播，似乎不太妥？

**Comment by yanglbme** [comment]
@bruceFend 有尊重版权，README 中有注明了，也给了各个书籍的购买链接。

当然，如果书籍作者觉得这样不好，请联系我删除书籍 PDF 资源。

**Comment by wzjaa** [comment]
可以告知提取码么🙂

**Comment by yanglbme** [comment]
@wzjaa 提取码就是 Resource 中的四位 code 。
