### ISSUE TITLE
这个仓库为什么有这么多star呢

### ISSUE THREAD

**Issue by atidat** [doocs/technical-books#41]
这里面看上去也没什么东西啊，就是些书籍名及类型分类，和购买链接，不明白为什么有这么多fork和star

**Comment by yanglbme** [comment]
总会有人需要的

**Comment by zhrgithub** [comment]
宝，你猜啊

**Comment by zhrgithub** [comment]
对啊  比如我就不太需要 但是喜欢啊

**Comment by yanglbme** [comment]
这个 issue 先关闭了哈，有问题随时提 issue，或者到 Discussions 讨论区交流。也欢迎提交 pr 参与本项目
