### ISSUE TITLE
豆瓣评分那么低的书为什么也可以加入，是不是夹带私货？

### ISSUE THREAD

**Issue by ikingye** [doocs/technical-books#42]
深度学习之 PyTorch 实战计算机视觉[2018]  豆瓣评分 4.7 分，确实是好书吗？

<img width="722" alt="image" src="https://user-images.githubusercontent.com/29562589/153816901-7341f582-540d-49e0-a0bb-e02e751172b6.png">

https://book.douban.com/subject/30231525/

**Comment by yanglbme** [comment]
确实评分有点低，你要不提个 pr 把它干掉？

**Comment by yanglbme** [comment]
我来处理一下吧，谢谢反馈
