### ISSUE TITLE
想问一下，怎么样才能有🈴️pull request的权限呢

### ISSUE THREAD

**Issue by haxianhe** [doocs/technical-books#5]

**Comment by yanglbme** [comment]
@haxianhe 你好，一般需要先提交 PR，我确保你的提交符合规范之后，便会邀请你成为项目的维护者。

**Comment by haxianhe** [comment]
> @haxianhe 你好，一般需要先提交 PR，我确保你的提交符合规范之后，便会邀请你成为项目的维护者。

好的，谢谢答疑，请问一下，我可以只添加书名，不放下载链接吗

**Comment by yanglbme** [comment]
@haxianhe 可以，注意区分书籍所属类别。
